version: "3"

services:
  frontend:
    container_name: tnt_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    container_name: tnt_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    container_name: tnt_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  seed:
    container_name: tnt_mongo_seed
    build:
      context: ./seed
      dockerfile: Dockerfile
    volumes:
      - ./seed/mongo-update.sh:/mongo-update.sh
    depends_on:
      - mongo

volumes:
  mongo-data:

